
services:
  userservice:
    build:
      context: .
      dockerfile: InnoShop.UserService.Presentation/Dockerfile
    container_name: userservice
    ports:
      - "7087:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development

  productservice:
    build:
      context: .
      dockerfile: InnoShop.ProductService.Presentation/Dockerfile
    container_name: productservice
    ports:
      - "7253:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development

  apigateway:
    build:
      context: .
      dockerfile: InnoShop.ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "7000:8080"
    depends_on:
      - userservice
      - productservice
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
